import type {
  AdminEmployee,
  AdminUser,
  RegistrationRequest,
} from "@/types/AdminApiTypes";

const DEMO_SUPER_ADMIN_PERMISSIONS: string[] = [
  "overview.view",
  "employees.view",
  "branches.view",
  "departments.view",
  "leave_types.view",
  "attendance.import",
  "registration_requests.view",
  "leave_requests.view",
  "job_positions.view",
];

const DEMO_DEPARTMENT_MANAGER_PERMISSIONS: string[] = [
  "overview.view",
  "employees.view",
  "leave_requests.view",
  "leave_requests.approve",
  "leave_requests.reject",
];

export const DEMO_SUPER_ADMIN: AdminUser = {
  id: "admin-1",
  name: "Layla Hassan",
  email: "admin@behr.com",
  role: "super_admin",
  permissions: DEMO_SUPER_ADMIN_PERMISSIONS,
};

export const DEMO_DEPARTMENT_MANAGER: AdminUser = {
  id: "admin-2",
  name: "Omar Khalil",
  email: "manager@behr.com",
  role: "department_manager",
  permissions: DEMO_DEPARTMENT_MANAGER_PERMISSIONS,
  department: "hr",
};

export const MOCK_ADMIN_EMPLOYEES: AdminEmployee[] = [
  {
    id: "emp-1",
    name: "Sara Ahmed",
    email: "sara.ahmed@behr.com",
    phone: "0501234567",
    fingerprintNumber: "100001",
    branch: "riyadh",
    department: "hr",
    position: "HR Specialist",
    joinedAt: "2024-03-12",
    status: "active",
  },
  {
    id: "emp-2",
    name: "Mohamed Ali",
    email: "mohamed.ali@behr.com",
    phone: "0502345678",
    fingerprintNumber: "100002",
    branch: "jeddah",
    department: "operations",
    position: "Operations Lead",
    joinedAt: "2023-11-05",
    status: "active",
  },
  {
    id: "emp-3",
    name: "Nour Ibrahim",
    email: "nour.ibrahim@behr.com",
    phone: "0503456789",
    fingerprintNumber: "100003",
    branch: "riyadh",
    department: "finance",
    position: "Accountant",
    joinedAt: "2025-01-18",
    status: "active",
  },
  {
    id: "emp-4",
    name: "Youssef Mahmoud",
    email: "youssef.m@behr.com",
    phone: "0504567890",
    fingerprintNumber: "100004",
    branch: "dammam",
    department: "it",
    position: "Software Engineer",
    joinedAt: "2024-08-22",
    status: "active",
  },
  {
    id: "emp-5",
    name: "Hana Saleh",
    email: "hana.saleh@behr.com",
    phone: "0505678901",
    fingerprintNumber: "100005",
    branch: "khobar",
    department: "sales",
    position: "Sales Executive",
    joinedAt: "2024-06-01",
    status: "inactive",
  },
  {
    id: "emp-6",
    name: "Khaled Farouk",
    email: "khaled.f@behr.com",
    phone: "0506789012",
    fingerprintNumber: "100006",
    branch: "riyadh",
    department: "hr",
    position: "Recruiter",
    joinedAt: "2025-02-10",
    status: "active",
  },
];

export const MOCK_REGISTRATION_REQUESTS: RegistrationRequest[] = [
  {
    id: "reg-1",
    name: "Amira Nasser",
    email: "amira.n@example.com",
    phone: "0507890123",
    fingerprintNumber: "200001",
    branch: "riyadh",
    department: "hr",
    position: "HR Coordinator",
    status: "pending",
    submittedAt: "2026-08-08",
  },
  {
    id: "reg-2",
    name: "Tariq Mansour",
    email: "tariq.m@example.com",
    phone: "0508901234",
    fingerprintNumber: "200002",
    branch: "jeddah",
    department: "operations",
    position: "Warehouse Supervisor",
    status: "pending",
    submittedAt: "2026-08-07",
  },
  {
    id: "reg-3",
    name: "Dina Mostafa",
    email: "dina.m@example.com",
    phone: "0509012345",
    fingerprintNumber: "200003",
    branch: "dammam",
    department: "finance",
    position: "Financial Analyst",
    status: "pending",
    submittedAt: "2026-08-06",
  },
  {
    id: "reg-6",
    name: "Hassan Youssef",
    email: "hassan.y@example.com",
    phone: "0502233445",
    fingerprintNumber: "200004",
    branch: "riyadh",
    department: "it",
    position: "Support Engineer",
    status: "pending",
    submittedAt: "2026-08-05",
  },
  {
    id: "reg-7",
    name: "Mariam Fahmy",
    email: "mariam.f@example.com",
    phone: "0503344556",
    fingerprintNumber: "200005",
    branch: "jeddah",
    department: "sales",
    position: "Sales Associate",
    status: "pending",
    submittedAt: "2026-08-04",
  },
  {
    id: "reg-8",
    name: "Karim Soliman",
    email: "karim.s@example.com",
    phone: "0504455667",
    fingerprintNumber: "200006",
    branch: "khobar",
    department: "operations",
    position: "Logistics Coordinator",
    status: "pending",
    submittedAt: "2026-08-03",
  },
  {
    id: "reg-9",
    name: "Nada Sherif",
    email: "nada.s@example.com",
    phone: "0505566778",
    fingerprintNumber: "200007",
    branch: "dammam",
    department: "hr",
    position: "Payroll Assistant",
    status: "pending",
    submittedAt: "2026-08-02",
  },
  {
    id: "reg-10",
    name: "Adel Hamza",
    email: "adel.h@example.com",
    phone: "0506677889",
    fingerprintNumber: "200008",
    branch: "riyadh",
    department: "finance",
    position: "Budget Analyst",
    status: "pending",
    submittedAt: "2026-08-01",
  },
  {
    id: "reg-11",
    name: "Salma Rashid",
    email: "salma.r@example.com",
    phone: "0507788990",
    fingerprintNumber: "200009",
    branch: "jeddah",
    department: "it",
    position: "QA Tester",
    status: "pending",
    submittedAt: "2026-07-31",
  },
  {
    id: "reg-12",
    name: "Fadi Nabil",
    email: "fadi.n@example.com",
    phone: "0508899001",
    fingerprintNumber: "200010",
    branch: "khobar",
    department: "sales",
    position: "Business Developer",
    status: "pending",
    submittedAt: "2026-07-30",
  },
  {
    id: "reg-4",
    name: "Rami Adel",
    email: "rami.a@example.com",
    phone: "0500123456",
    fingerprintNumber: "200011",
    branch: "riyadh",
    department: "hr",
    position: "Training Specialist",
    status: "approved",
    submittedAt: "2026-07-28",
  },
  {
    id: "reg-5",
    name: "Lina Hossam",
    email: "lina.h@example.com",
    phone: "0501122334",
    fingerprintNumber: "200012",
    branch: "khobar",
    department: "sales",
    position: "Account Manager",
    status: "rejected",
    submittedAt: "2026-07-20",
  },
];
